theme: jekyll-text-theme

plugins:
  - jekyll-titles-from-headings

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

# Optional TeXt-specific settings:
text_skin: default        # or choose 'dark', 'forest', etc.
highlight_theme: tomorrow # code highlighting style